name: BedWars
version: 2.3
api: [3.0.0-ALPHA11]
main: GPlug\Bedwars
author: 
 - Bluplayz
 - MrKiAN
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [BW-PM]
    Start:
        description: Bedwars Forcestart Command
